aevea/release-notary

- internal/history/commit_text.go
- CommitMessage returns message of given commit
> history: add commit_text

- internal/text/trim_message.go
- TrimMessage returns only the first line of commit message
> text: add trim_message

- internal/text/build_history.go
- BuildHistory takes commit messages and builds a complete list
> text: add build_history

- internal/history/previous_tag.go
- fixes generating changelog when current commit is not a tag
> history: fix case where current commit is not tag

- README.md
- adds example usage
- updates build status badge
> readme: Add example usage

- Makefile
- builder.sh
> makefile: remove useless build command

- cmd/log.go
- cmd/root.go
- internal/history/current_commit.go
- adds flag to cmd
- adds debug output to current commit
- references #30
> feat(debug): add debug for current commit

- cmd/log.go
- internal/history/previous_tag.go
- adds verbose output to previous_tag functionality
- references #30
> feat(debug): add debug to previous_tag

- .drone.yml
- Dockerfile
- Makefile
- add releasing of docker image to Dockerhub
- updates build function in Makefile
> feat: release docker image

- README.md
- expected-output.md
- in order to show what a user can expect
> docs: add expected output

- internal/text/emoticons.go
- add constants for emoticons compatible with Github
> feat: Emoticons

- internal/text/split_sections.go
- internal/text/split_sections_test.go
- further categorisation for preparation of release notes
> feat: splitSections

- internal/text/release_notes.go
- internal/text/release_notes_test.go
- formats Sections for expected output
> feat: ReleaseNotes

- internal/releaser/docs.go
- internal/releaser/provider.go
- internal/releaser/release.go
- internal/releaser/releaser.go
- Releaser will be used as a wrapper for releasing to different platforms
> feat: Releaser

- internal/text/split_sections.go
- internal/text/split_sections_test.go
- fix was added to other section despite being a bug fix
> fix: fix was not added to bug category

- action.yml
- will allow for publishing to Github Actions
> feat: Add Github action file

- README.md
- expected-output.md
- improves usage section
- documents required variables
- adds github action documentation
> docs: readme improvements

- .github/workflows/linters.yml
- upgrades commitsar action to latest
> chore(ci): upgrade commitsar

- cmd/publish.go
- internal/gitlab/client.go
- internal/gitlab/latest_release.go
- internal/gitlab/publish.go
- internal/gitlab/service.go
- internal/releaser/releaser.go
- adds support for full publishing run in Gitlab
- adds gitlab to the publish command
References #35, #36
> feat(releaser): add Gitlab release service

- internal/gitlab/check_existing_release.go
- internal/gitlab/publish.go
- gitlab service will now check for existing release and change method according to that
> feat(gitlab): check existing release

- cmd/publish.go
- previously would result in a panic
> feat: warn when no service has been selected

- .drone.yml
> chore(ci): pin Docker versions

- cmd/get_commits.go
- cmd/log.go
- go.mod
- go.sum
> chore: update git to v1.2.1

- go.mod
- go.sum
- previous release accidentally broke the flow returning more results than expected
> chore(deps): upgrade git to v1.2.3

- cmd/publish.go
- adds cobra flag which toggles simple mode
> feat: add simpleouput flag

- internal/gitlab/latest_release.go
- internal/gitlab/latest_release_test.go
- internal/gitlab/publish_test.go
- internal/gitlab/testdata/latest_release.json
- adds tests for API calls going to Gitlab
- fixes bad documentation link in LatestRelease
> tests(gitlab): improve testing

- expected-output-simple.md
- expected-output.md
- internal/text/build_single_commit.go
- internal/text/commit.go
- internal/text/parse_commits.go
- internal/text/parse_commits_test.go
- internal/text/release_notes_test.go
> feat(text): Parse references in commit body

- expected-output-simple.md
- expected-output.md
- internal/text/build_heading.go
- internal/text/release_notes_test.go
> feat(release-notes): move emoji before title name

- .github/workflows/test.yml
- README.md
- adds badges for releases
- adds badge for test
- makes test job run on master as well for added safety
> chore: add badging to the project

- .github/workflows/build.yml
- .github/workflows/release.yml
- fixes pushing to dockerhub for latest version
- fixes goreleaser
> fix(ci): latest versions not pushed to dockerhub

- README.md
This causes some potential security risks. Huge thanks to @Ry0taK
Refs #257
> fix: README contains links to old organization

- internal/slack/release_notes.go
> fix(slack): github squash format breaks formatting

- README.md
Closes #321 
Signed-off-by: Baptiste Roux <baptiste.roux@skale-5.com>
> docs: Update gitlab-ci.yml example to override entrypoint

- Dockerfile
- Makefile
Simplify parts and unify the approach with the one in commitsar.
> fix(ci): Docker build in Kaniko failing
