- cmd/log.go
- replaces i = 0; etc. with range
> chore: improve syntax is log.go

- go.mod
- internal/text/urls.go
- internal/text/urls_test.go
- LinkToCommit formats urls according to Github style
> feat: LinkToCommit

- internal/text/categorize_commits.go
- internal/text/categorize_commits_test.go
- adds functionality to categorise commits according to category and scope
- this is a pre-requisite for building the release notes
> feat: CategoriseCommits

- Dockerfile
BREAKING CHANGE: previously log was the default command in the Dockerfile. It is now replaced with publish.
- Publish allows users to publish to Github right now
> feat(Dockerfile)!: set default Dockerfile command to publish

- cmd/publish.go
- publish command will now pass commit hash info into release notes function
- allows for a richer release note format with links to exact commits
> feat: pass commit hash to release note generator

- internal/text/release_notes.go
- internal/text/release_notes_test.go
- internal/text/split_sections.go
- internal/text/split_sections_test.go
- in order to add extra information such as Hash it's important that the whole Commit object is passed down
- also allows for extra grouping based on scope
> improvement: pass Commit object in split_section and release_notes

- .goreleaser.yml
- changelog is handled by release notary therefore there is no need to have goreleaser handle it additionally
> chore: skip changelog in goreleaser

- cmd/publish.go
- internal/text/commit.go
- internal/text/parse_commits.go
- internal/text/release_notes.go
- internal/text/release_notes_test.go
- adds short version of commit hash to release notes
- moves Commit into commit.go
- adds Hash as a type with String() method
> feat: add Commit hashes to release notes

- internal/gitlab/latest_release.go
- internal/gitlab/publish.go
- gitlab, unlike github, does not create a release per tag
- this will get the message from the tag and create a new release
> fix(gitlab): use tags instead of releases api

- internal/gitlab/publish.go
- PUT is used only to update, in this case we are creating a new Release
> chore(gitlab): use POST instead of PUT

- internal/gitlab/latest_release.go
- internal/gitlab/publish.go
- internal/gitlab/service.go
- uses existing metadata from tag GET to determine if release notes are already attached
> fix(gitlab): use existing release information to adjust method

- internal/gitlab/publish.go
- release was done correctly, but app would fail
- gitlab uses 201 to signify that a new release was attached to an existing tag
> fix(gitlab): publisher would crash on 201 code

- internal/releaser/release.go
- Release Notary will now check that the release it is adding text to doesn't contain the same text
> feat(releaser): don't release if a release already exists

- cmd/publish.go
- on new repos PreviousTag is not available, this would result in a crash
> fix: don't crash when prvious tag is not available

- cmd/publish.go
- go.mod
- in new repositories previous tag is not available, this will allow for iterating all unreleased commits
> fix: add all commits if previous tag is not available

- .github/workflows/linters.yml
Instead of having to build the thing every time, it should use the docker image that you are already building.
> chore(ci): Use docker image

- expected-output.md
- internal/text/release_notes_test.go
- makes the test and expected output to be fully 1 to 1
- makes sure that the user is getting exactly what is advertised
> tests(text): load expected output from file

- internal/text/release_notes.go
- internal/text/release_notes_test.go
- internal/text/split_sections.go
- internal/text/split_sections_test.go
BREAKING CHANGE: Sections struct has been removed. 
- maps are now used instead. This is a pre-requisite for dynamic mappings using a config file.
> chore!: rework release notes to use maps

- internal/text/build_commit_log.go
- internal/text/build_heading.go
- internal/text/build_section.go
- internal/text/build_single_commit.go
- internal/text/release_notes.go
- release_notes file was getting too big, this simply break it up
> refactor: break up release note builder in separate files

- cmd/publish.go
- internal/text/build_commit_log.go
- internal/text/build_heading.go
- internal/text/build_section.go
- internal/text/build_single_commit.go
- internal/text/release_notes.go
- internal/text/release_notes_test.go
- to avoid having to pass down settings through many functions
> refactor: use struct for ReleaseNote methods

- expected-output-simple.md
- internal/text/build_commit_log.go
- internal/text/build_section.go
- internal/text/build_single_commit.go
- internal/text/build_single_commit_test.go
- internal/text/release_notes_test.go
- internal/text/sections.go
- updates expected output files to provide an example of simple and full outputs
- adds logic for handling new lines (Markdown requires two empty spaces followed by a newline to correctly create a new line in text)
- adds logic for open by default in the feature section
- adds collapsible sections
Closes #132
> feat: build full commit

- internal/text/parse_commits.go
- internal/text/parse_commits_test.go
- commit body was not being parsed by ParseCommitMessage
- simplifies the logic for parsing the commit to use named groups instead of using match indexes like before
> fix: parse commit body

- .drone.yml
- cmd/publish.go
- internal/slack/publish.go
- internal/slack/publish_test.go
- internal/slack/release_notes.go
- internal/slack/release_notes_test.go
- internal/slack/slack.go
- internal/slack/testdata/expected_format.md
If SLACK_WEBHOOK is set then Release Notary will send a simple Slack markdown compliant message to it.
> feat(slack): add basic integration with Slack

- cmd/publish.go
- internal/text/build_single_commit.go
- internal/text/release_notes.go
- internal/text/release_notes_test.go
BREAKING CHANGE: simple output is now the default output. Complex output is hidden under the --complex flag.
Switches Simple output as the default one.
Changes simple flag -> complex flag.
> refactor(cmd)!: set simple output as default

- expected-output-simple.md
- expected-output.md
- internal/text/build_single_commit.go
- internal/text/release_notes_test.go
Makes all simple outputs a list which makes markdown formatting easier.
> refactor(text): add - delimiter

- go.mod
- go.sum
- internal/slack/gitremorter_mock_test.go
- internal/slack/publish.go
- internal/slack/publish_test.go
- internal/slack/release_notes.go
- internal/slack/release_notes_test.go
- internal/slack/slack.go
- updates outillage/integrations to v0.3.0
- previous approach was causing issues in tests as it was also testing the logic inside outillage/integrations instead of testing just release notes
- integrations would get the env variables leading to failing tests
> fix(tests): rework publish to use GitRemoter interface

- README.md
actions/checkout@v2 behaves differently than the first version.
Therefore the README needs an update.
> docs: update documentation for actions/checkout@v2

- .gitignore
- internal/text/build_history.go
- internal/text/build_single_commit.go
- internal/text/release_notes_test.go
- internal/text/split_sections_test.go
- internal/text/trim_message.go
- internal/text/trim_message_test.go
- internal/text/urls_test.go
The way github auto squash formats messages would break the relase notes.
Closes #299
> fix(github): squash commits done by github broken

- internal/gitlab/publish_test.go
- internal/gitlab/service.go
Remove legacy unused name field
Fixes https://github.com/aevea/release-notary/issues/308
> fix(GitLab): Named release
